### PR TITLE
Fix gstreamer decoder after #3664

### LINKED ISSUE #3752: Unable to build liquidsoap with gstreamer
**Describe the bug**
Liquidsoap cannot be built with *gstreamer* enabled since #3665.

<details>
<summary>Build error</summary>

```
#=== ERROR while compiling liquidsoap-core.2.2.4-1 ============================#
# context     2.1.5 | linux/x86_64 | ocaml-base-compiler.4.14.1 | https://opam.ocaml.org#8b5a0a33
# path        ~/.opam/4.14.1/.opam-switch/build/liquidsoap-core.2.2.4-1
# command     ~/.opam/4.14.1/bin/dune build -p liquidsoap-core -j 5 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/liquidsoap-core-13391-20ab37.env
# output-file ~/.opam/log/liquidsoap-core-13391-20ab37.out
### output ###
# (cd _build/default && /root/.opam/4.14.1/bin/ocamlc.opt -w -40 -g -bin-annot -I src/core/.liquidsoap_gstreamer.objs/byte -I /root/.opam/4.14.1/lib/angstrom -I /root/.opam/4.14.1/lib/bigstringaf -I /root/.opam/4.14.1/lib/bytes -I /root/.opam/4.14.1/lib/camlp-streams -I /root/.opam/4.14.1/lib/camomile/lib -I /root/.opam/4.14.1/lib/cry -I /root/.opam/4.14.1/lib/curl -I /root/.opam/4.14.1/lib/dto[...]
# File "src/core/decoder/gstreamer_decoder.ml", line 314, characters 37-51:
# 314 |       (Decoder.test_file ~log ~mimes:mime_types#get
#                                            ^^^^^^^^^^^^^^
# Error: This expression has type string list
#        but an expression was expected of type Decoder.stream list option
```

</details>

**To Reproduce**
1. `docker run -it --rm debian:bookworm-slim bash`
1. ```sh
   OPAM_VERSION=2.1.5;
   OCAML_VERSION=4.14.1;
   ```
   ```sh
   apt-get update;
   apt-get dist-upgrade;
   apt-get install --no-install-recommends -y curl ca-certificates patch unzip bubblewrap git bzip2 gcc make libc6-dev g++;
   curl -sS -L -o /usr/local/bin/opam "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-x86_64-linux";
   chmod +x /usr/local/bin/opam;
   opam init --bare --disable-sandboxing -n;
   opam switch create "$OCAML_VERSION";
   eval $(opam env --switch="$OCAML_VERSION");
   opam install --confirm-level=unsafe-yes liquidsoap gstreamer;
   ```

**Expected behavior**
No build error when *gstreamer* is enabled.

**Version details**

- OS: *Debian 12*
- Version: *2.2.4*

**Install method**
opam

**Common issues**
#3665
#3751

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #3752

### CODE REVIEW

**Comment by toots** [comment]
Thank you for this work! How critical is `gstreamer` for you? Are you actively using and does it work for you.

We are considering deprecating it in favor of `ffmpeg`. Would that be an acceptable alternative for you if we did so?

**Comment by vbgl** [comment]
I don’t use `liquidsoap`. I’ve just observed that in its latest release, there is an ill-typed program that the build system will actively try to build. So here is a bug fix.

**Comment by toots** [comment]
gstreamer has been removed. Thanks for the contribution nonetheless!

**Comment by zvarnell** [comment]
Without `gstreamer`, is there a way to pick up dynamic changes to the playlist? From my understanding `ffmpeg ` only reads on start.

**Comment by toots** [comment]
@zvarnell can you describe the use case more?

**Comment by zvarnell** [comment]
I am creating an uninterrupted 24/7 video stream that picks up pre-recorded content and broadcasts it back to back. I was running into issues using ffmpeg without temporarily ending the stream to re-read the playlist file. 

I think I have it figured out using ffplayout, although I'm not sure how they do it.

**Comment by toots** [comment]
Without more details it's hard to tell you more :-)

Is the input over HTTP? Or another protocol?

**Pull request closed without merging**
