### PR TITLE
Proper parsing of string litterals.

### PR DESCRIPTION
**Pull request by toots**
I think this is fine. I'm not sure what `incrline` is for so I'm leaving this here for review..

### CODE REVIEW

**Comment by smimram** [comment]
Do we really have to double backslashes in liquidsoap files? Apparently we now have to type \\# instead of \#, etc. This is both heavy and non backward-compatible...

**Comment by toots** [comment]
Can you give me an example, @smimram ? I can't reproduce here:
```
# This is a test

x = "this is \
  another test # \ \""

print(x)
```

```
% ./liquidsoap /tmp/test.liq
Warning: illegal backslash escape in string.
this is another test # \ "
No output defined, nothing to do.
```

Simple backlash will work but generate a warning. I've tried to model it after OCaml's string parsing. We use `"%S"` to print strings so it makes sense to also parse them the same way so that we're idempotent here. I'm open to suggestions, though, of course :-)

**Comment by smimram** [comment]
I did not really try but saw lots of changes such as
```
 -    l = string.split(separator='([^=]+\s*=\s*"(\\"|[^"])*")\s*,\s*',s)
 +    l = string.split(separator='([^=]+\\s*=\\s*"(\\"|[^"])*")\\s*,\\s*',s)
```
where `\s` becomes `\\s`...

**Comment by toots** [comment]
This will be fixed when #408 is merged.

**Pull request closed without merging**
