### PR TITLE
Make url normalization optional, add warning when normalization changes the url.

### PR DESCRIPTION
**Pull request by toots**
Fixes: #3789

### CODE REVIEW

**Comment by elizaveta-markova** [comment]
I get "... or use 'normalize_url=false.'" But use it how? The only relevant operator I call is playlist, and playlist doesn't accept that argument.

**Comment by toots** [comment]
Hi @elizaveta-markova ! I think that this for the upcoming `2.3.0` version only!

**Comment by toots** [comment]
Ha sorry my bad it should also be in https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.2.x

The changes are indeed only applied to the `http.get` and similar functions. Let me double check that we do need them for `playlist`.

**Comment by elizaveta-markova** [comment]
Thank you, Romain. Incidentally, the messages seem to be false positives,
anyway. I don't see any difference between the two names that are said to
be different, and the files play.

BTW I did not file anything here on the other issue I mentioned on Discord.
It's not a bug, just me trying to explain what happened. But I don't think
what I was trying to do is supposed to work, anyway. A stream of a still
image followed by a video doesn't really make sense: it should just be a
short looping video followed by the main video.

Thanks for the software and the charming book. It's much more than I have
any need for, but I've had fun and learned a lot.

Liz

**Comment by toots** [comment]
Thanks!

This message is confusing and also the parameter might not be available for instance when a URL is resolved through the file resolution protocol. 

I added a global setting and improved the message:

```
          "Requested url %s is different from normalized url: %s. URL are \
           normalized by default to ensure maximum compatibility with e.g. \
           URLs with spaces in them. However, this can also cause issues so we \
           recommend passing normalized URLs. Url normalization can be \
           disabled on a case-by-case basis using the  `normalize_url=false` \
           parameter or globally using the `settings.http.normalize_url` \
           setting."
```

Hope this will make more sense!

**Comment by elizaveta-markova** [comment]
Setting is good. But you've got %s and %s in the message. Is that why I
can't see a difference?

**Comment by toots** [comment]
Yes, sorry it is populated with the actual URLs.

**Comment by elizaveta-markova** [comment]
Populated, yes, but with the same thing twice, rather than with the two putatively different names? Or can %s and %s refer to two different strings?

**Comment by toots** [comment]
One will be the original stream passed to the function and the other the normalized URL. If they differ, this can create issues so the log is here to surface and explain what is going on.

**Pull request merged**
