### PR TITLE
Fix SRT shutdown

### PR DESCRIPTION
**Pull request by toots**
Fixes: #965

### CODE REVIEW

**Comment by toots** [comment]
@mbugeia Any chance you could try this branch? The test `.deb` should be coming up soon..

**Comment by mbugeia** [comment]
I get the (almost) same error.

```2019/09/21 18:10:38 [mksafe:3] Switch to safe_blank.
^C2019/09/21 18:10:40 [threads:2] Queue generic queue #2 crashed with exception Error(Einvparam,Operation not supported: Bad parameters)
Raised at file "src/srt.ml", line 73, characters 11-37
Called from file "src/srt.ml", line 283, characters 10-156
Called from file "io/srt_io.ml", line 89, characters 8-92
Called from file "duppy.ml", line 394, characters 20-24
Called from file "duppy.ml", line 151, characters 61-77
Called from file "duppy.ml", line 279, characters 14-23
Called from file "duppy.ml", line 313, characters 7-24
Called from file "duppy.ml", line 356, characters 5-9
Called from file "tools/tutils.ml", line 204, characters 19-55
```

**Comment by toots** [comment]
Arf! Can you try now?

**Comment by mbugeia** [comment]
Still the same

```2019/09/22 19:25:31 [mksafe:3] Switch to safe_blank.
^C2019/09/22 19:25:34 [main:3] Shutdown started!
2019/09/22 19:25:34 [main:3] Waiting for main threads to terminate...
2019/09/22 19:25:34 [threads:2] Queue generic queue #2 crashed with exception Error(Einvparam,Operation not supported: Bad parameters)
Raised at file "src/srt.ml", line 73, characters 11-37
Called from file "src/srt.ml", line 283, characters 10-156
Called from file "io/srt_io.ml", line 89, characters 8-92
Called from file "duppy.ml", line 394, characters 20-24
Called from file "duppy.ml", line 151, characters 61-77
Called from file "duppy.ml", line 279, characters 14-23
Called from file "duppy.ml", line 313, characters 7-24
Called from file "duppy.ml", line 356, characters 5-9
Called from file "tools/tutils.ml", line 204, characters 19-55```

**Pull request closed without merging**
