### PR TITLE
Print methods separately

### PR DESCRIPTION
**Pull request by smimram**
Documents returned methods outside the type. For instance, the doc of `amplify` was
```
Multiply the amplitude of the signal.

Type: (?id : string, ?override : string?, {float},
 source(audio='b, video='c, midi='d)) -> source(audio='b, video='c, midi='d)
.{
  time : () -> float,
  shutdown : () -> unit,
  fallible : () -> bool,
  skip : () -> unit,
  seek : (float) -> float,
  is_up : () -> bool,
  remaining : () -> float,
  on_track : ((([string * string]) -> unit)) -> unit,
  on_shutdown : ((() -> unit)) -> unit,
  on_metadata : ((([string * string]) -> unit)) -> unit,
  is_ready : () -> bool,
  id : (() -> string)}

Category: Source / Sound Processing

Parameters:

 * id : string (default: "")
     Force the value of the source ID.

 * override : string? (default: "liq_amplify")
     Specify the name of a metadata field that, when present and well-formed,
     overrides the amplification factor for the current track. Well-formed
     values are floats in decimal notation (e.g. `0.7`) which are taken as
     normal/linear multiplicative factors; values can be passed in decibels
     with the suffix `dB` (e.g. `-8.2 dB`, but the spaces do not matter).

 * (unlabeled) : {float} (default: None)
     Multiplicative factor.

 * (unlabeled) : source(audio='b, video='c, midi='d) (default: None)
```
and with this PR it becomes
```
Multiply the amplitude of the signal.

Type: (?id : string, ?override : string?, {float},
 source(audio='b, video='c, midi='d)) -> source(audio='b, video='c, midi='d)

Category: Source / Sound Processing

Parameters:

 * id : string (default: "")
     Force the value of the source ID.

 * override : string? (default: "liq_amplify")
     Specify the name of a metadata field that, when present and well-formed,
     overrides the amplification factor for the current track. Well-formed
     values are floats in decimal notation (e.g. `0.7`) which are taken as
     normal/linear multiplicative factors; values can be passed in decibels
     with the suffix `dB` (e.g. `-8.2 dB`, but the spaces do not matter).

 * (unlabeled) : {float} (default: None)
     Multiplicative factor.

 * (unlabeled) : source(audio='b, video='c, midi='d) (default: None)

Methods:

 * id : () -> string

 * is_ready : () -> bool

 * on_metadata : ((([string * string]) -> unit)) -> unit

 * on_shutdown : ((() -> unit)) -> unit

 * on_track : ((([string * string]) -> unit)) -> unit

 * remaining : () -> float

 * is_up : () -> bool

 * seek : (float) -> float

 * skip : () -> unit

 * fallible : () -> bool

 * shutdown : () -> unit

 * time : () -> float
```
(the above example supposes that #1465 has been merged).

Next step would be to add proper documentation for methods, but this PR gets readability of documentation back to acceptable I think.

### CODE REVIEW

**Review by toots — COMMENTED** [review]
Is there a way to connect the methods to a certain type/value? If I look at the message right now, it's not clear where the methods do apply..

**Comment by smimram** [comment]
For now I only extract the methods from the returned value, so there should be no ambiguity there (the methods in the arguments are still indicated as before, thus #1465 to reduce their number).

**Comment by toots** [comment]
What happens if the operator returns more than one source?

**Comment by toots** [comment]
I was thinking of something like this:
```
Multiply the amplitude of the signal.

Type: (?id : string, ?override : string?, {float},
 source(audio='b, video='c, midi='d)) -> source(audio='b, video='c, midi='d) as var

Category: Source / Sound Processing

Parameters:

 * id : string (default: "")
     Force the value of the source ID.

 * override : string? (default: "liq_amplify")
     Specify the name of a metadata field that, when present and well-formed,
     overrides the amplification factor for the current track. Well-formed
     values are floats in decimal notation (e.g. `0.7`) which are taken as
     normal/linear multiplicative factors; values can be passed in decibels
     with the suffix `dB` (e.g. `-8.2 dB`, but the spaces do not matter).

 * (unlabeled) : {float} (default: None)
     Multiplicative factor.

 * (unlabeled) : source(audio='b, video='c, midi='d) (default: None)

var methods:

 * id : () -> string

 * is_ready : () -> bool

 * on_metadata : ((([string * string]) -> unit)) -> unit

 * on_shutdown : ((() -> unit)) -> unit

 * on_track : ((([string * string]) -> unit)) -> unit

 * remaining : () -> float

 * is_up : () -> bool

 * seek : (float) -> float

 * skip : () -> unit

 * fallible : () -> bool

 * shutdown : () -> unit

 * time : () -> float
```

With possibly more `var`

**Comment by smimram** [comment]
I agree with you, but I think we can leave this for a second time, correctly naming subtypes will take some more work...

**Comment by toots** [comment]
Works for me, this is clearly an improvement.

**Pull request merged**
