### PR TITLE
Improve doc for `rms()` and `peak()`

### PR DESCRIPTION
**Pull request by Yamakaky**
Fix https://github.com/savonet/liquidsoap/issues/781

### CODE REVIEW

**Comment by toots** [comment]
Thanks! @smimram how do you want to coordinate this with your current work? Should we merge this directly in the markdown formatted doc?

**Comment by Yamakaky** [comment]
Oh, OK, I can resubmit it after the migration!

**Comment by toots** [comment]
@Yamakaky or you can submit directly there. I believe we won't change the doc here while this effort is underway. Thanks very much for the contribution tho!

**Comment by smimram** [comment]
Yes, it great to have contributions :)

**Pull request merged**
