### PR TITLE
Resample using ffmpeg.

### PR DESCRIPTION
**Pull request by smimram**
Not tested yet, but should work pretty well :)

### CODE REVIEW

**Comment by smimram** [comment]
This can be merged in my opinion. You can test with
```
set("log.level", 5)
set("audio.converter.samplerate.preferred", "ffmpeg")

s = playlist("~/Music")
s = mksafe(s)
s = stretch(ratio=1.2, s)
output.pulseaudio(s)
```

**Comment by toots** [comment]
Look good to me, thanks!

**Comment by smimram** [comment]
Thanks for merging! BTW, it seems to be better than samplerate with which we are secretly loosing some samples sometimes...

**Comment by toots** [comment]
Ho wow. Wanna make it the default before samplerate when found?

**Comment by smimram** [comment]
I think it could be a good idea, yes. Where is the default chosen?

**Comment by toots** [comment]
@smimram here: https://github.com/savonet/liquidsoap/blob/master/src/converters/audio_converter.ml#L55
You might want to switch this to an array like we do for decoders..

**Pull request merged**
