### PR TITLE
Make encoder header more robust by using a callback.

### PR DESCRIPTION
**Pull request by toots**
Fixes: #3265

### CODE REVIEW

**Comment by DigiBC** [comment]
@toots

Maybe I'm too late because you're working on a fix already, but here's an observation of the original issue that I'd like to share with you:
Most streaming clients fail with an error while VLC keeps the HTTP connection and continues "listening". As soon as there's a track change in Liquidsoap which results in a new logical OGG stream, VLC suddenly starts playback. (VLC playback isn't seamless on track changes, but that's a flaw of VLC.)

**Comment by toots** [comment]
@DigiBC yeah that tracks. We had a mechanism to keep the last ogg header on hand to send to the client on initial connection and it got broken somehow. This PR fixes it.

Couple of things worth noting:
* FFmpeg is bad with chained ogg streams so `input.http` might not be super well behaved with live ogg streams
* The header support is only for the various internal `%ogg` encoder (including `%vorbis` and etc). It won't work with `%ffmpeg` ogg support. It should work with `%wav` tho, which is nice but anecdotical.

Overall, and quite regretfully, looking at back over time really shows that the ogg spec for chaining tracks is pretty bad. It was never well understood or implemented correctly and we might have had it wrong for some formats for years too (see [this explanation](https://www.liquidsoap.info/blog/2023-05-17-ogg-compliance/)).

At this point, I would recommend _avoiding_ the ogg container unless you are willing to strip all track marks and metadata. The number of decoder/clients who get it wrong is just too big.

**Comment by DigiBC** [comment]
@toots

Many thanks for the explanation!
I agree that OGG FLAC has quite some flaws, but so far I've had only good experience with <code>output.harbor</code> feeding a digital radio audio encoder with built-in GStreamer and ICY metadata support on the same machine. The stream works perfectly and without any glitches for months...
I'd like to continue to do that.   :relaxed:

**Comment by toots** [comment]
Ha yes, if you have control over the listener or for a limited exposure it's a different story of course.

**Comment by DigiBC** [comment]
After testing the artefact _liquidsoap-fix-3265_2.3.0-ubuntu-jammy-1_amd64.deb_ I can confirm that it works again!
Thank you!
:thumbsup:

**Comment by toots** [comment]
Great! Just pushed the patch to the next rolling release!

**Pull request merged**
