### PR TITLE
Make hls output write atomic.

### PR DESCRIPTION
**Pull request by toots**
Fixes: #3284

### CODE REVIEW

**Comment by BusterNeece** [comment]
@toots Running into this error now on our Docker installations:

```
 Source /var/azuracast/stations/azuratest_radio/hls/live_m3u8 failed while streaming: Sys_error("Invalid cross-device link")!
2023/08/02 05:05:32 [clock.main:2] Raised by primitive operation at Hls_output.hls_output#open_out.object#close in file "src/core/outputs/hls_output.ml", line 548, characters 16-44
2023/08/02 05:05:32 [clock.main:2] Re-raised at Hls_output.hls_output#open_out.object#close in file "src/core/outputs/hls_output.ml", line 553, characters 16-52
2023/08/02 05:05:32 [clock.main:2] Called from Hls_output.hls_output#close_segment.(fun) in file "src/core/outputs/hls_output.ml", line 568, characters 13-51
2023/08/02 05:05:32 [clock.main:2] Called from Stdlib__Option.map in file "option.ml", line 24, characters 57-62
2023/08/02 05:05:32 [clock.main:2] Called from Hls_output.hls_output#close_segment in file "src/core/outputs/hls_output.ml", line 566, characters 8-924
2023/08/02 05:05:32 [clock.main:2] Called from Hls_output.hls_output#write_pipe.(fun) in file "src/core/outputs/hls_output.ml", line 945, characters 13-33
2023/08/02 05:05:32 [clock.main:2] Called from Stdlib__Option.map in file "option.ml", line 24, characters 57-62
2023/08/02 05:05:32 [clock.main:2] Called from Hls_output.hls_output#write_pipe in file "src/core/outputs/hls_output.ml", line 941, characters 8-226
2023/08/02 05:05:32 [clock.main:2] Called from Stdlib__List.iter2 in file "list.ml", line 147, characters 24-31
2023/08/02 05:05:32 [clock.main:2] Called from Output.encoded#send_frame.output_chunks.f in file "src/core/outputs/output.ml", line 238, characters 10-24
2023/08/02 05:05:32 [clock.main:2] Called from Output.output#output in file "src/core/outputs/output.ml", line 179, characters 45-70
2023/08/02 05:05:32 [clock.main:2] Called from Clock.MkClock.clock#end_tick.(fun) in file "src/core/clock.ml", line 318, characters 16-24
```

**Comment by toots** [comment]
Thanks @BusterNeece. It would appear that the temporary directory is on a different file system than the hls directory.

I just pushed changes in `main` and `rolling-release-v2.2.x` to:
1. Fallback to non-atomic file write instead of failing
2. Add an optional `temp_dir` option to `output.hls` to make it possible to specify a temporary directory in the same file system.

Would you be kind enough to check that these two changes do work for you? The script should now run by default but in degraded, non-atomic mode and you should be able to specify a temporary directory in the same partition, restoring atomic write operations.

Commit is https://github.com/savonet/liquidsoap/commit/49c1c276a5147196956a3802d5741efb48c2d1bb in main and https://github.com/savonet/liquidsoap/commit/47464a4dbd04e7b7629ab168ebac7f928154bced in `rolling-release-v2.2.x`

Thanks!

**Comment by BusterNeece** [comment]
@toots Thanks, will update to that. Seems the CI is red since that commit went live so we don't have a release asset for it yet.

**Comment by toots** [comment]
@BusterNeece should be good now.

**Pull request merged**
