### PR TITLE
Cue in/out and fade in/out/type in `ffmpeg2wav`

### PR DESCRIPTION
**Pull request by toots**
Test script:
```
# Optional:
set("protocol.ffmpeg2wav.metadata",true)
set("protocol.ffmpeg2wav.replaygain",true)

def next() =
  path = list.hd(default="",get_process_lines("find /tmp/bla | grep mp3 | sort -R | head -n 1"))

  cross_duration = random.float(min=7.,max=12.)
  fade_in = random.float(min=5.,max=7.)
  fade_out = random.float(min=5.,max=7.)

  cue_in = random.float(min=2.,max=15.)
  cue_out = random.float(min=17.,max=25.)

  req = "ffmpeg2wav:annotate:liq_cue_in=\"#{cue_in}\",liq_cue_out=\"#{cue_out}\",liq_cross_duration=\"#{cross_duration}\",liq_fade_in=\"#{fade_in}\",liq_fade_out=\"#{fade_out}\":#{path}"
  request.create(req)
end

s = request.dynamic(next)

def transition(_,_,_,_,old,new) =
  add(normalize=false,[new,old])
end

s = cross(transition,s)
```

cc/ @RM-FM

### CODE REVIEW

**Comment by RM-FM** [comment]
@toots Just started testing. First thing I noted is that title meta data is missing:

```
s = request.dynamic(get_request) # this is where ffmpeg2wav:annotate takes place
s = on_track(trigger_metadata, s) # title meta data missing here
s = cross(transition,s)
```

**Comment by RM-FM** [comment]
@toots 2nd thing is that the `cross_duration` value is either ignored or not used the same was as before. Next track starts clearly too early.

**Comment by RM-FM** [comment]
@toots Unfortunately the glitches are still there even with this pre-decoded approach.

**Comment by toots** [comment]
I definitely see metadata with the script above. I've even refined it to be sure:
```
set("protocol.ffmpeg2wav.metadata",true)
set("protocol.ffmpeg2wav.replaygain",true)

def next() =
  path = list.hd(default="",get_process_lines("find /tmp/bla | grep mp3 | sort -R | head -n 1"))

  cross_duration = random.float(min=7.,max=12.)
  fade_in = random.float(min=5.,max=7.)
  fade_out = random.float(min=5.,max=7.)

  cue_in = random.float(min=2.,max=15.)
  cue_out = random.float(min=17.,max=25.)

  req = "ffmpeg2wav:annotate:liq_cue_in=\"#{cue_in}\",liq_cue_out=\"#{cue_out}\",liq_cross_duration=\"#{cross_duration}\",liq_fade_in=\"#{fade_in}\",liq_fade_out=\"#{fade_out}\":#{path}"
  request.create(req)
end

s = request.dynamic(length=60.,next)

def print(m) =
  print("got metadata: #{m}")
end

s = on_metadata(print,s)

def transition(_,_,_,_,old,new) =
  add(normalize=false,[new,old])
end

s = cross(transition,s)
```

Log:
```
2019/08/07 17:11:09 [decoder.wav/aiff:4] WAV header read (44100 Hz, 16 bits, 1432936 bytes), starting decoding...
got metadata: [("album", "L'int\195\169grale (vol. 9)"), ("track", "16"), ("kind", "{audio=2;video=0;midi=0}"), ("artist", "Serge Gainsbourg"), ("decoder", "WAV"), ("title", "Je n'avais qu'un seul mot \195\160 lui dire"), ("filename", "/var/folders/0m/yj55_5x901j3f6f9lff57z8w0000gn/T/liq-process24cf23.wav"), ("temporary", "true"), ("source", "request.dynamic_7338"), ("initial_uri", "ffmpeg2wav:annotate:liq_cue_in=\"10.3716836995\",liq_cue_out=\"18.4949048672\",liq_cross_duration=\"8.7727996807\",liq_fade_in=\"5.93972455905\",liq_fade_out=\"6.98444925509\":/tmp/bla/Serge Gainsbourg/L'inte\204\129grale (vol. 9)/16 Je n'avais qu'un seul mot a\204\128 lui dire.mp3"), ("encoder", "Lavf58.20.100"), ("status", "playing"), ("on_air", "2019/08/07 17:11:09"), ("rid", "0")]
2019/08/07 17:11:09 [cross_7365:4] More buffering will be needed.
```

However, `liq_fade_duration` was indeed lost, I just brought it back to the final request so it should be detected by `cross`:
```
2019/08/07 17:14:01 [cross_7370:4] Setting crossfade duration to 10.51s
2019/08/07 17:14:01 [cross_7370:4] More buffering will be needed.
```

Lastly, I am surprised that you do still hear the glitches. If you log with level `4`, you should see the `ffmpeg` commands issued to prepare the file, if you grab one that has a glitch and reproduce it locally, what do you hear?

**Comment by RM-FM** [comment]
We are currently facing an issue with the installation of the latest build. But I can already say that the decoded WAV files are clean and free from any glitches. To me it seems that the issue occurs during/at the end of the actual crossfade.

**Comment by RM-FM** [comment]
Finally we've managed to install the latest build:

- Metadata is available now
- Glitches at the end of the crossfade are still there (even if WAV files are fine)
- Replay gain extraction seems to fail (no further information; please see log)
- There is a 1 or 2 second fade at the beginning even if `liq_fade_in` is set to 0.0 (please check audio sample)

```
2019/08/08 10:54:40 [extract.replaygain:4] Replaygain extraction failed: 
2019/08/08 10:54:40 [protocol.process:4] Processing wav,ffmpeg -y -i $(input) -ac 2  -t 7.23750019073 -af afade=in$(colon)st=0.0$(colon)d=0.0,afade=out$(colon)st=4.86910009384$(colon)d=2.36840009689  "/tmp/liq-process6d2993.wav":/home/autodj/musik/Dropin 01.mp3
2019/08/08 10:54:40 [protocol.process:4] Executing ffmpeg -y -i "/home/autodj/musik/Dropin 01.mp3" -ac 2  -t 7.23750019073 -af afade=in:st=0.0:d=0.0,afade=out:st=4.86910009384:d=2.36840009689  "/tmp/liq-process6d2993.wav"
```

[liq-process6d2993.wav.mp3.zip](https://github.com/savonet/liquidsoap/files/3480847/liq-process6d2993.wav.mp3.zip)

**Comment by RM-FM** [comment]
There is an issue with the clean up procedure as well... Seems that short tracks are not beeing deleted automatically.

image

**Comment by RM-FM** [comment]
Is the fade-in/out fix also relevant for the Master branch?

**Comment by toots** [comment]
@RM-FM, I cannot reproduce the temp file leak unfortunately..

**Pull request merged**
