### PR TITLE
Implement input.v4l2 using ffmpeg.

### PR DESCRIPTION
**Pull request by smimram**

### CODE REVIEW

**Comment by smimram** [comment]
This is not working for now, we get lots of
```
2020/08/24 16:49:46 [input(dot)ffmpeg:2] Feeding stopped: FFmpeg.Avutils.Error(Invalid argument).
```
@toots any idea?

**Comment by toots** [comment]
Let's revisit that once #1310 is merged, I'm also gonna try to add support for ffmpeg raw frames to this operator.

**Comment by toots** [comment]
How's this going?

**Comment by smimram** [comment]
This was (re)done in 70b72dc63c37acc07e0a332e0b980a0a281f5f8b.

**Pull request closed without merging**
