### PR TITLE
Use glob for stdlib install.

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by smimram** [comment]
This is much better, thanks! Do you think, we could also use this to remove `dune.inc` in tests?

**Comment by toots** [comment]
> This is much better, thanks! Do you think, we could also use this to remove `dune.inc` in tests?

Not really, no. There's no support for a `each` or `map` operation on those it seems.

**Comment by toots** [comment]
This PR would require rebuilding all docker images.. I think it unfortunately has too limited benefits vs. cost at the moment. Maybe after the `2.2.x` release?

**Comment by smimram** [comment]
No need to rush as long as it gets merged at some point!

**Review by smimram — APPROVED** [review]

**Comment by toots** [comment]
This is done now,

**Pull request closed without merging**
