### PR TITLE
Prometheus implementation on Liquidsoap side.

### PR DESCRIPTION
**Pull request by smimram**
@toots it would be nice if you could help me restore this code in order to test frames... Thanks!

### CODE REVIEW

**Comment by gibix** [comment]
Hello! there is a plan to merge this for 2.0?

**Comment by smimram** [comment]
Prometeus support will definitely be part of 2.0. This PR is only to test its implementation in Liquidsoap side instead of OCaml.

**Comment by toots** [comment]
Prometheus is already supported in `1.4.4` actually but there was an issue that prevented it from being added to the online doc. I'll see about this and will also add a specific section about it in the documentation.

**Comment by toots** [comment]
You can find an example of its use here: https://github.com/mbugeia/srt2hls/blob/master/radio/live.liq

**Pull request closed without merging**
