### PR TITLE
Add on_frame.

### PR DESCRIPTION
**Pull request by smimram**

### CODE REVIEW

**Comment by toots** [comment]
Let's hold on to that for a second if you don't mind, I'm not sure that the proposed use for it is warranted.

**Comment by smimram** [comment]
Yes, no rush, it was only a proposal.

**Comment by toots** [comment]
Closing this as we realized executing script stuff on a pre-frame basis is a very bad idea!

**Comment by smimram** [comment]
With recent improvements in the language I'd like to reopen this one.

**Comment by smimram** [comment]
Let's merge this, we'll see what can be done with it.

**Pull request merged**
