### PR TITLE
Autocue: Removed fade curve and delay calculations

### PR DESCRIPTION
**Pull request by RM-FM**
Removed liq_fade_in_curve, liq_fade_out_curve and liq_fade_out from autocue. If needed these can be set individually using the crossfade callback.

### CODE REVIEW

**Review by RM-FM — COMMENTED** [review]
Typo in description: Removed `liq_fade_out_delay` but not `liq_fade_out`, obviously!

**Review by toots — APPROVED** [review]
Thanks!

**Comment by RM-FM** [comment]
@toots `@citest` failed an prevents PR from being merged. Is there anything than I can do, to make that test succeed?

**Comment by RM-FM** [comment]
@toots took note of unused variable "fade_out_delay" and removed it

**Pull request merged**
