### PR TITLE
Add AWS protocol setting for different endpoint URLs.

### PR DESCRIPTION
**Pull request by RecursiveGreen**
I'm proposing to add an additional setting for the s3:// protocol that allows to set the endpoint URL for the S3 bucket. This will enable other S3-like implementations (like Digital Ocean's Spaces) to work.

### CODE REVIEW

**Comment by toots** [comment]
Looks great! Would you mind adding a `CHANGES` entry? Then I'll be happy to merge!

**Comment by RecursiveGreen** [comment]
Done.

**Comment by toots** [comment]
Awesome, thanks. I've added some credit to you! Merging now.

**Comment by RecursiveGreen** [comment]
Thanks! I didn't even think to add myself.

**Pull request merged**
