### PR TITLE
Accept empty playlists when reloading fallible playlists.

### PR DESCRIPTION
**Pull request by toots**
Partial fix for issue #203

### CODE REVIEW

**Comment by toots** [comment]
@dbaelde: doest that look good to you?

**Comment by dbaelde** [comment]
Your proposal preserves infallibility, so that's good. However it changes a behavior on which people may be relying currently: on a fallible playlist (most of the cases) a failed reload used to have no effect, now it empties the playlist. This should not be taken lightly. I don't have a clear picture of how broken playlists appear in practice, though. Moreover, some new features (reload on change) could justify a change of behavior, pushing people to use the new features where appropriate.

**Comment by giflw** [comment]
I can use an example to make more clear to usefulness of this kind of behavior.

Suppose one have two `playlist` in a  `rotate`: one for music and one for spots. Those playlist are marked to reload each round. So, as I know, in each rotation they will try to reload. Suppose there are no spots to play during some hours, so a empty playlist will be given. After that time window, new spots appear, and than, spots are played again.

To not change current behavior, could be added a parameter like `accept_empty` with `false` as default.

**Comment by dbaelde** [comment]
@giflw did you consider using a dummy URI (e.g. "/path/to/nowhere") to obtain an empty playlist. As dumb as it sounds, I suspect several people use it since I've been mentioning it several times over the years. It might be preferable that you also use this workaround, instead of changing the behavior of a very important source. A new and cleaner behavior should be reserved for a major release, for which backwards compatibility is not promised.

**Comment by toots** [comment]
I think this behavior makes total sense to me and is more natural. I'm merging this so we can start testing it.

**Pull request merged**
