### PR TITLE
IPv6 support for input.harbor. ref: #190

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by codeofdusk** [comment]
How can I apply these commits to my local copy? I installed using opam.

**Comment by toots** [comment]
```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout input.harbor-ipv6
opam pin add liquidsoap .
```

You will need `autoconf` and `automake` for this I believe.

**Comment by codeofdusk** [comment]
=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Rsync partially failed:
          symlink has no referent: "/home/codeofdusk/liquidsoap/bootstrap"
          rsync error: some files/attrs were not transferred (see previous
          errors) (code
          23) at main.c(1183) [sender=3.1.1]

[liquidsoap.dev] /home/codeofdusk/liquidsoap/ synchronized

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of liquidsoap failed at "./bootstrap".
Processing  1/1: [liquidsoap: rm]
#=== ERROR while installing liquidsoap.dev ====================================#
# opam-version 1.2.2
# os           linux
# command      ./bootstrap
# path         /home/codeofdusk/.opam/system/build/liquidsoap.dev
# compiler     system (4.02.3)
# exit-code    127
# env-file     /home/codeofdusk/.opam/system/build/liquidsoap.dev/liquidsoap-24832-6d07ae.env
# stdout-file  /home/codeofdusk/.opam/system/build/liquidsoap.dev/liquidsoap-24832-6d07ae.out
# stderr-file  /home/codeofdusk/.opam/system/build/liquidsoap.dev/liquidsoap-24832-6d07ae.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install liquidsoap dev
No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of
       sync.

**Comment by toots** [comment]
Damn I forgot. Git modules are so annoying.. Try again:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout input.harbor-ipv6
opam pin add liquidsoap .
```

**Comment by codeofdusk** [comment]
Git submodule init/update worked.

Bill

**Pull request merged**
